create table transactions (
WEEK_END_DATE date,
STORE_NUM BIGINT,
UPC BIGINT,
UNITS INT,
VISITS INT,
HHS INT,
SPEND FLOAT,
PRICE FLOAT,
BASE_PRICE FLOAT,
FEATURE INT,
DISPLAY INT,
TPR_ONLY INT);

COPY transactions(WEEK_END_DATE,STORE_NUM,UPC,UNITS,VISITS,HHS,SPEND,PRICE,BASE_PRICE,FEATURE,DISPLAY,TPR_ONLY) from '/home/olksndr/project/transactions.csv' DELIMITER ',' CSV HEADER;

alter table transactions 
rename price to stock_price ;
alter table transactions 
RENAME base_price to price;

update transactions
set spend = price * units;


create table products (
UPC BIGINT, 
DESCRIPTION TEXT, 
MANUFACTURER TEXT, 
CATEGORY TEXT, 
SUB_CATEGORY TEXT,
PRODUCT_SIZE TEXT);


COPY products(UPC,DESCRIPTION,MANUFACTURER,CATEGORY,SUB_CATEGORY,PRODUCT_SIZE) from '/home/olksndr/project/products.csv' DELIMITER ',' CSV HEADER;


create table stores(
STORE_ID BIGINT,
STORE_NAME TEXT,
ADDRESS_CITY_NAME TEXT,
ADDRESS_STATE_PROV_CODE TEXT,
MSA_CODE TEXT,
SEG_VALUE_NAME TEXT,
PARKING_SPACE_QTY BIGINT,
SALES_AREA_SIZE_NUM BIGINT,
AVG_WEEKLY_BASKETS BIGINT);

COPY stores(STORE_ID,STORE_NAME,ADDRESS_CITY_NAME,ADDRESS_STATE_PROV_CODE,MSA_CODE,SEG_VALUE_NAME,PARKING_SPACE_QTY,SALES_AREA_SIZE_NUM,AVG_WEEKLY_BASKETS) from '/home/olksndr/project/stores.csv' DELIMITER ',' CSV HEADER;

alter table stores
rename store_id to store_num;

